
---
  # Configure default site for testing

- name: Perform standard tasks
  include_tasks: std_tasks.yml

- name: copy default.conf
  template:
    src: default.conf
    dest: "{{ resty_sites_dir }}/default.conf"
