# @Author: Haupt Joshua
# @Date:   15-Apr-2018
# @Email:  josh@hauptj.com
# @Filename: main.yml
# @Last modified by:   Haupt Joshua
# @Last modified time: 01-May-2018

---
  # Driver for OpenResty Installation
  # Ref: https://www.digitalocean.com/community/tutorials/how-to-use-the-openresty-web-framework-for-nginx-on-ubuntu-16-04

- name: Compile from source
  include_tasks: source.yml
  when: resty_install_from_source == true

- name: Install form repo
  include_tasks: repo.yml
  when: resty_install_from_source == false

  ##### Post Installation Tasks #####

- name: copy systemd service file #for CentOS
  template:
    src: openresty.service
    dest: /etc/systemd/system/openresty.service

  # Plain HTTP server
- name: configure default site for testing
  include_tasks: default_site.yml
  when: resty_default_server == true

  # CV Server
- name: configure CV site
  include_tasks: cv.yml
  when: resty_default_server == false and resty_cv_server == true

  # HTTP server configured for WordPress
- name: configure wordpress site
  include_tasks: wordpress.yml
  when: resty_default_server == false and resty_cv_server == false and resty_install_wp == true

- name: insert firewalld rule for nginx port {{ nginx_port }}
  firewalld:
    port: "{{ nginx_port }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  ignore_errors: yes
  when: firewalld_installed == true
