---
  # Driver for OpenResty Installation

- name: Compile from source
  import_tasks: source.yml
  when: openresty_install_from == source

- name: Install form repo
  import_tasks: repo.yml
  when: openresty_install_from == repo
