---
  # Install OpenResty from the official repository

- name: CentOS OpenResty Installation
  block:
    # https://openresty.org/package/centos/openresty.repo
    - name: Add OpenResty Repository
      yum_repository:
        name: openresty
        description: Official OpenResty Open Source Repository for CentOS
        baseurl: https://openresty.org/package/centos/$releasever/$basearch
        skip_if_unavailable: no
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: https://openresty.org/package/pubkey.gpg
        enabled: yes

    - name: Install OpenResty and Resty-CLI on CentOS
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - openresty
        - openresty-resty

  when: ansible_distribution == "CentOS"

- name: Ubuntu OpenResty Installation
  block:

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: latest
        update_cache: yes

    - name: Add an Apt signing key for OpenResty repo
      apt_key:
        url: https://openresty.org/package/pubkey.gpg
        state: present

    - name: Install OpenResty repository
      apt_repository:
        repo: deb https://openresty.org/package/ubuntu {{ansible_distribution_release}} main
        state: present

    - name: Install OpenResty and Resty-CLI on Ubuntu
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - openresty
        - openresty-resty

  when: ansible_distribution == "Ubuntu"
