# @Author: Haupt Joshua <HauptJ>
# @Date:   26-Mar-2018
# @Email:  josh@hauptj.com
# @Filename: wordpress.yml
# @Last modified by:   HauptJ
# @Last modified time: 02-Apr-2018

---
  # OpenResty site configuration

- name: Perform standard tasks
  include_tasks: std_tasks.yml

# TODO: check for presence of php info page during CI testing
- name: copy info.php as STUB
  template:
    src: info.php
    dest: "{{ resty_default_web_dir }}/"
  when: resty_ci_test == true

- name: Install python-passlib to use htpasswd module
  yum:
    name: python-passlib
    state: present

- name: Generate password file for wp-admin directory
  htpasswd:
    path: "{{ resty_sites_dir }}/.htpasswd"
    name: "{{ htpasswd_user }}"
    password: "{{ htpasswd_pass }}"
    crypt_scheme: md5_crypt

- name: Copy nginx configuration for wordpress
  template:
    src: wp.conf
    dest: "{{ resty_sites_dir }}/default.conf"

- name: Enable OpenResty
  service:
    name: openresty
    state: started
    enabled: yes
  ignore_errors: yes
  notify: restart openresty
