---
  # OpenResty site configuration

- name: Perform standard tasks
  include_tasks: std_tasks.yml

- name: copy info.php as STUB
  template:
    src: info.php
    dest: "{{ resty_default_web_dir }}/"
  when: resty_ci_test == true

- name: Install python-passlib to use htpasswd module
  yum:
    name: python-passlib
    state: present

- name: Generate password file for wp-admin directory
  htpasswd:
    path: "{{ resty_sites_dir }}/.htpasswd"
    name: "{{ htpasswd_user }}"
    password: "{{ htpasswd_pass }}"
    crypt_scheme: md5_crypt

- name: Copy nginx configuration for wordpress
  template:
    src: wp.conf
    dest: "{{ resty_sites_dir }}/default.conf"
